import argparse
def main():
    # 解析命令行参数
    parser = argparse.ArgumentParser()
    parser.add_argument("--name", required=True, help="要问候的对象")
    args = parser.parse_args()
    if not args.name.strip():
        parser.error("--name 不能只包含空白字符")
    # 打印结果，加入你的姓名标识
    print(f"Hello {args.name}!  Generated by 赵均临(25020007178)")
# 双击直接运行也支持的入口
if __name__ == "__main__":
    main()
